sudo: required
services:
  - docker

before_install:
  - docker build -t xjohnx/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xjohnx/react-test npm test

after_success:
  - docker build -t xjohnx/multi-client ./client
  - docker build -t xjohnx/multi-server ./server
  - docker build -t xjohnx/multi-nginx ./nginx
  - docker build -t xjohnx/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker repository
  - docker push xjohnx/multi-client 
  - docker push xjohnx/multi-nginx
  - docker push xjohnx/multi-server
  - docker push xjohnx/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucker_name: elasticbeanstalk-us-east-2-411545023520
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  

